spring:
  redis:
    redisson:
      file: classpath:redisson.yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://<mysql-host-ip>:<mysql-port>/<databaseName>?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: <mysql-username>
    password: <mysql-password>
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: <mybatis-module-package>
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      sac:
        demo:
          mapper : debug